# Generated by Django 6.0.7 on 2026-07-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('amazon_locker', 'Amazon Locker'), ('amazon_counter', 'Amazon Counter'), ('alt_store', 'Alternative store')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pickup_code', models.CharField(blank=True, max_length=20)),
                ('is_vine', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('state', models.CharField(choices=[('in_transit', 'In transit'), ('awaiting_pickup', 'Awaiting pickup'), ('picked_up', 'Picked up'), ('returned', 'Returned')], default='in_transit', max_length=20)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='packages.pickuppoint')),
            ],
            options={
                'ordering': ['-actual_arrival', '-estimated_arrival'],
            },
        ),
    ]
