# Generated by Django 6.0.7 on 2026-07-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='asin',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='package',
            name='barcode_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='package',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='package',
            name='ordered_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='picked_up_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='shipment_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='package',
            name='shipped_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawemail',
            name='kind',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rawemail',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rawemail',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='packages.package'),
        ),
        migrations.AddField(
            model_name='rawemail',
            name='parse_error',
            field=models.TextField(blank=True),
        ),
    ]
