# Generated by Django 6.0.7 on 2026-07-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_asin_package_barcode_url_package_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.CharField(choices=[('in_transit', 'In transit'), ('awaiting_pickup', 'Awaiting pickup'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='in_transit', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='kind',
            field=models.CharField(choices=[('amazon_locker', 'Amazon Locker'), ('amazon_counter', 'Amazon Counter'), ('alt_store', 'Alternative store'), ('home', 'Entrega a domicilio')], max_length=20),
        ),
    ]
