# Generated by Django 6.0.7 on 2026-07-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_state_alter_pickuppoint_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='location_key',
            field=models.CharField(blank=True, db_index=True, max_length=5),
        ),
    ]
