# Generated by Django 6.0.7 on 2026-07-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_merge_duplicate_pickup_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='carrier',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='package',
            name='carrier_tracking_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='kind',
            field=models.CharField(choices=[('amazon_locker', 'Amazon Locker'), ('amazon_counter', 'Amazon Counter'), ('alt_store', 'Alternative store'), ('home', 'Entrega a domicilio'), ('carrier', 'Transportista')], max_length=20),
        ),
    ]
