# Generated by Django 6.0.7 on 2026-07-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_package_carrier_package_carrier_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='estimated_arrival_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
