# Generated by Django 6.0.7 on 2026-07-25 11:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_package_estimated_arrival_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eu_import_surcharge', models.DecimalField(decimal_places=2, default=Decimal('3.63'), help_text='Recargo aduanero de la UE que los vendedores de fuera de la Unión repercuten al cliente. Un pedido Vine con recargo cuesta exactamente esta cifra en el correo de envío en lugar de 0,00€. Ponlo a 0 para desactivar la excepción.', max_digits=6)),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuración',
            },
        ),
    ]
