# Generated by Django 6.0.7 on 2026-07-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_reflag_vine_with_eu_surcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='item_kind',
            field=models.CharField(choices=[('package', 'Paquete'), ('letter', 'Carta')], default='package', max_length=10),
        ),
        migrations.AddField(
            model_name='package',
            name='recipient',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='kind',
            field=models.CharField(choices=[('amazon_locker', 'Amazon Locker'), ('amazon_counter', 'Amazon Counter'), ('alt_store', 'Alternative store'), ('home', 'Entrega a domicilio'), ('carrier', 'Transportista'), ('pepe_y_dalda', 'Pepe y Dalda')], max_length=20),
        ),
    ]
