# Generated by Django 6.0.7 on 2026-07-31 19:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_package_item_kind_package_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='pepe_addresses',
            field=models.TextField(blank=True, default="Regència d'Urgell\nPepe y Dalda", help_text='Direcciones que en realidad son Pepe y Dalda, una por línea. Un pedido de Amazon enviado a una de ellas se clasifica como Pepe y Dalda en lugar de como entrega a domicilio. Basta un fragmento de la línea de destino del correo (la calle, por ejemplo); no distingue mayúsculas, acentos ni apóstrofos. Déjalo vacío para desactivarlo.', verbose_name='direcciones que en realidad son Pepe y Dalda'),
        ),
        migrations.AlterField(
            model_name='config',
            name='eu_import_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.63'), help_text='Recargo aduanero de la UE que los vendedores de fuera de la Unión repercuten al cliente. Un pedido Vine con recargo cuesta exactamente esta cifra en el correo de envío en lugar de 0,00€. Ponlo a 0 para desactivar la excepción.', max_digits=6, verbose_name='recargo aduanero de la UE'),
        ),
    ]
