# Generated by Django 6.0.7 on 2026-07-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_config_pepe_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='display_name',
            field=models.CharField(blank=True, help_text='Nombre corto que se muestra en el calendario y en las fichas, en lugar del nombre completo del correo. Déjalo vacío para mostrar el nombre completo.', max_length=60, verbose_name='nombre para mostrar'),
        ),
    ]
