# Generated by Django 6.0.7 on 2026-08-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_pickuppoint_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='suggestions_month',
            field=models.DateField(blank=True, help_text='Día 1 del mes al que pertenece el contador de arriba. Lo escribe la propia aplicación.', null=True, verbose_name='mes que cuenta el contador'),
        ),
        migrations.AddField(
            model_name='config',
            name='suggestions_per_month',
            field=models.PositiveIntegerField(default=30, help_text='Máximo de sugerencias que se le pueden pedir a la API en un mes natural. Cuenta los intentos, no los aciertos: un intento que falla puede haberse cobrado igual. Ponlo a 0 para desactivar las sugerencias.', verbose_name='sugerencias de borrador al mes'),
        ),
        migrations.AddField(
            model_name='config',
            name='suggestions_used',
            field=models.PositiveIntegerField(default=0, help_text='Cuántas van pedidas dentro del mes que dice el campo siguiente. Se reinicia solo al cambiar de mes; ponlo a 0 para devolver el cupo a mano.', verbose_name='sugerencias gastadas este mes'),
        ),
    ]
