# Generated by Django 6.0.7 on 2026-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_config_suggestions_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='suggestion_examples',
            field=models.PositiveIntegerField(default=10, help_text='Cuántas reseñas de referencia se envían como ejemplo: primero las marcadas como fijas, luego las más recientes. 0 no envía ninguna.', verbose_name='reseñas de referencia por propuesta'),
        ),
        migrations.AddField(
            model_name='config',
            name='suggestion_prompt',
            field=models.TextField(blank=True, help_text='Instrucciones con las que se redacta la propuesta de borrador. Marcadores disponibles: {producto}, {estrellas}, {notas} y {ejemplos}. Vacío desactiva la función.', verbose_name='plantilla de la propuesta'),
        ),
    ]
