# Generated by Django 6.0.7 on 2026-08-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_config_suggestion_examples_config_suggestion_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='suggestion_examples',
        ),
    ]
