# Generated by Django 6.0.7 on 2026-09-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_remove_config_suggestion_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Enlace de Google Maps para navegar al punto. Si se pega un enlace con origen o búsqueda, se limpiará automáticamente para iniciar la ruta hacia el destino.', max_length=500, verbose_name='enlace de Google Maps'),
        ),
    ]
