"""
Django settings for harvest project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Local dev keeps its secrets (the Gmail credentials) in a gitignored .env; on
# the Pi docker-compose injects real environment variables, which win because
# load_dotenv never overrides an already-set variable.
load_dotenv(BASE_DIR / '.env')


# Everything below is read from the environment so the same image runs in dev
# and on the Pi. What's missing falls back to the *production-safe* value, not
# to the `startproject` one: an install that configures nothing is treated as
# production, and development opts in explicitly with DJANGO_DEBUG=True in its
# .env. The defaults used to run the other way round, which meant a
# DJANGO_DEBUG that ever went missing from docker-compose would have served
# tracebacks over the public tunnel. A variable disappearing has to fail
# closed.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
#
# The development key below is *published* — this is a public repository — so
# it is only ever handed out with DEBUG on. Refusing to boot without a real one
# is the whole point: an app on the tunnel signing CSRF tokens with a key
# anybody can read would do it silently, and nothing would ever look wrong.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY no está definida. Harvest no arranca en '
            'producción con la clave de desarrollo: está publicada en el '
            'repositorio.'
        )
    SECRET_KEY = 'django-insecure-ve-zktzror9t3utu8+)yakto*9r#paz*%-dw9u69w)3jhge9il'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]

# The Cloudflare Tunnel terminates TLS and forwards plain HTTP, so Django needs
# this header to know the original request was HTTPS (affects CSRF checks and
# secure-cookie behavior).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS]

# The whole site is only ever served over HTTPS once behind the Cloudflare
# Tunnel. Tied to DEBUG so local http:// dev is unaffected.
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'packages',
    'reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'harvest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'harvest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH', BASE_DIR / 'db.sqlite3'),
        # web and the ingest worker share this file from two containers;
        # wait out the other's writes instead of failing "database is locked".
        'OPTIONS': {'timeout': 20},
    }
}


# Gmail ingestion — IMAP with an App Password on the dedicated mailbox. The
# Gmail API was ruled out: `gmail.readonly` is a restricted scope and
# Testing-mode tokens expire every 7 days. Empty by default: ingestion
# commands must refuse to run rather than guess.
GMAIL_IMAP_HOST = os.environ.get('GMAIL_IMAP_HOST', 'imap.gmail.com')
GMAIL_IMAP_USER = os.environ.get('GMAIL_IMAP_USER', '')
GMAIL_IMAP_APP_PASSWORD = os.environ.get('GMAIL_IMAP_APP_PASSWORD', '')

# Move successfully-processed emails to Gmail's Trash (auto-deleted after 30
# days) so the inbox self-cleans and stays a trigger, not an archive. The raw
# email is saved to the DB first, and failures are kept in the inbox, so this
# is safe and reversible. Off by default (dev safety); the Pi turns it on.
GMAIL_TRASH_PROCESSED = os.environ.get('GMAIL_TRASH_PROCESSED', 'false').lower() == 'true'

# Draft suggestions for the reviews module (see reviews/suggest.py). Empty by
# default and empty everywhere today: `suggest.is_configured()` reads these,
# and the UI offers the feature only when both are set — so an unconfigured
# install says so instead of failing at the press of a button. The style
# guide that shapes the wording is not here: it lives in the database,
# tunable without a deploy.
SUGGEST_API_URL = os.environ.get('SUGGEST_API_URL', '')
SUGGEST_API_KEY = os.environ.get('SUGGEST_API_KEY', '')
SUGGEST_MODEL = os.environ.get('SUGGEST_MODEL', '')
# Extra headers the endpoint requires, one `Nombre: valor` per line. Here
# rather than in the code so nothing a particular service happens to need is
# written down in a public repository.
SUGGEST_API_HEADERS = os.environ.get('SUGGEST_API_HEADERS', '')


# Logging: single console handler, timestamps in Europe/Madrid, so the whole
# ingestion audit trail is one `docker logs` away and reads in local time.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'harvest': {
            '()': 'packages.logformat.LocalTimeFormatter',
            'format': '{asctime} [{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'harvest'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        # Our own logs at INFO; quiet Django's per-request noise.
        'packages': {'level': 'INFO'},
        'django.request': {'level': 'WARNING'},
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Spanish UI: month/weekday names from the `date` template filter and the
# whole admin come out translated for free.
LANGUAGE_CODE = 'es'

# The calendar's whole job is answering "what happens today / this week",
# so "today" must be the user's today, not UTC's.
TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
