# Generated by Django 6.0.7 on 2026-07-16 21:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0003_alter_package_state_alter_pickuppoint_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='VineCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(unique=True)),
                ('ends_on', models.DateField()),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('asin', models.CharField(blank=True, db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('published', 'Publicada')], default='pending', max_length=20)),
                ('draft', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True)),
                ('review_id', models.CharField(blank=True, max_length=20)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='packages.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
