# Generated by Django 6.0.7 on 2026-07-16 22:11

from datetime import date
from django.db import migrations


def create_cycles(apps, schema_editor):
    VineCycle = apps.get_model('reviews', 'VineCycle')
    cycles = []

    # Vine cycles are exactly 6 months apart: 27 Jan – 26 Jul, 27 Jul – 26 Jan.
    # Generate from 2020 to 2030 for historical coverage.
    for year in range(2020, 2031):
        # Jan 27 – Jul 26
        cycles.append(VineCycle(
            starts_on=date(year, 1, 27),
            ends_on=date(year, 7, 26)
        ))
        # Jul 27 – Jan 26 (next year)
        cycles.append(VineCycle(
            starts_on=date(year, 7, 27),
            ends_on=date(year + 1, 1, 26)
        ))

    VineCycle.objects.bulk_create(cycles, ignore_conflicts=True)


def reverse_cycles(apps, schema_editor):
    VineCycle = apps.get_model('reviews', 'VineCycle')
    VineCycle.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_cycles, reverse_cycles),
    ]
