# Generated by Django 6.0.7 on 2026-07-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_populate_vine_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text_is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
