# Generated by Django 6.0.7 on 2026-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_correct_cycle_boundaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('draft', 'Borrador'), ('approved', 'Aprobada'), ('published', 'Publicada')], default='pending', max_length=20),
        ),
    ]
