# Generated by Django 6.0.7 on 2026-08-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='draft',
            new_name='suggestion',
        ),
        migrations.AddField(
            model_name='review',
            name='suggestion_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
