# Generated by Django 6.0.7 on 2026-08-02 14:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_suggestion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='producto')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='estrellas')),
                ('title', models.CharField(max_length=255, verbose_name='titular')),
                ('text', models.TextField(verbose_name='texto')),
                ('is_example', models.BooleanField(default=True, help_text='Desmárcalo para que deje de enviarse como ejemplo sin perder el texto. Las reseñas que llegan solas y resultan ser casi la propuesta tal cual entran ya desmarcadas.', verbose_name='usar como ejemplo')),
                ('is_pinned', models.BooleanField(default=False, help_text='Las fijas van siempre en el lote de ejemplos, antes que las recientes. Reserva unas pocas para tus mejores reseñas.', verbose_name='fija')),
                ('added_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='añadida el')),
                ('source_review', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference', to='reviews.review', verbose_name='reseña de origen')),
            ],
            options={
                'verbose_name': 'reseña de referencia',
                'verbose_name_plural': 'reseñas de referencia',
                'ordering': ['-is_pinned', '-added_on', '-pk'],
            },
        ),
    ]
