# Generated by Django 6.0.7 on 2026-08-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_referencereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencereview',
            options={'ordering': ['added_on', 'pk'], 'verbose_name': 'reseña de referencia', 'verbose_name_plural': 'reseñas de referencia'},
        ),
        migrations.RemoveField(
            model_name='referencereview',
            name='is_example',
        ),
        migrations.RemoveField(
            model_name='referencereview',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='referencereview',
            name='source_review',
        ),
    ]
